"""Paper-faithful Multiscreen implementation."""

from multiscreen.config import MultiscreenConfig
from multiscreen.corpus_build import (
    CorpusBuildReport,
    CorpusBuildSpec,
    CorpusBuildSplit,
    CorpusDatasetSource,
    CorpusSourceBuildReport,
    CorpusSplitBuildReport,
    allocate_source_document_counts,
    build_corpus_from_spec,
    iterate_source_texts,
    load_corpus_build_spec,
    normalize_corpus_text,
)
from multiscreen.corpus import (
    CorpusSplit,
    TokenizedCorpusArtifact,
    TokenizedCorpusMetadata,
    build_fixed_causal_lm_batches,
    build_token_stream_from_corpus,
    expand_corpus_paths,
    iter_corpus_documents,
    load_corpus_documents,
    load_tokenized_corpus_artifact,
    save_tokenized_corpus_artifact,
    split_token_stream,
    tokenize_corpus_documents,
    write_token_stream_from_corpus,
)
from multiscreen.data import CausalLMBatch, causal_lm_batch_from_token_block, sample_token_blocks
from multiscreen.generation import generate_tokens, sample_next_token, truncate_prompt_tokens
from multiscreen.math import TanhNorm, apply_mipe, build_softmask, normalize_unit, trim_and_square
from multiscreen.model import GatedScreeningTile, MultiscreenLM, ScreeningUnit
from multiscreen.sizing import (
    MultiscreenSizeEstimate,
    estimate_multiscreen_size_from_token_count,
    multiscreen_parameter_count,
    multiscreen_parameter_count_from_dimensions,
    multiscreen_parameter_count_from_psi,
)
from multiscreen.train import OptimizerConfig, TrainStepResult, build_optimizer, causal_lm_loss, evaluate_loss, model_device, train_step

__all__ = [
    "CausalLMBatch",
    "CorpusBuildReport",
    "CorpusBuildSpec",
    "CorpusBuildSplit",
    "CorpusDatasetSource",
    "CorpusSplit",
    "CorpusSourceBuildReport",
    "CorpusSplitBuildReport",
    "GatedScreeningTile",
    "MultiscreenConfig",
    "MultiscreenLM",
    "MultiscreenSizeEstimate",
    "OptimizerConfig",
    "ScreeningUnit",
    "TanhNorm",
    "TokenizedCorpusArtifact",
    "TokenizedCorpusMetadata",
    "TrainStepResult",
    "allocate_source_document_counts",
    "apply_mipe",
    "build_fixed_causal_lm_batches",
    "build_optimizer",
    "build_softmask",
    "build_corpus_from_spec",
    "build_token_stream_from_corpus",
    "causal_lm_batch_from_token_block",
    "causal_lm_loss",
    "estimate_multiscreen_size_from_token_count",
    "evaluate_loss",
    "expand_corpus_paths",
    "generate_tokens",
    "iter_corpus_documents",
    "iterate_source_texts",
    "load_corpus_documents",
    "load_corpus_build_spec",
    "load_tokenized_corpus_artifact",
    "model_device",
    "multiscreen_parameter_count",
    "multiscreen_parameter_count_from_dimensions",
    "multiscreen_parameter_count_from_psi",
    "normalize_corpus_text",
    "normalize_unit",
    "sample_next_token",
    "save_tokenized_corpus_artifact",
    "sample_token_blocks",
    "split_token_stream",
    "tokenize_corpus_documents",
    "train_step",
    "truncate_prompt_tokens",
    "trim_and_square",
    "write_token_stream_from_corpus",
]
